# Data settings
DATA_DIR: "data/clean"
IMAGE_SIZE: 227
NUM_CLASSES: 2 # (Tumor vs. No-Tumor)
CLASSES: ['notumor', 'tumor']

# Model settings
MODEL_NAME: "CNN_C1"

# Training settings
BATCH_SIZE: 32
EPOCHS: 50
LEARNING_RATE: 0.0002
DEVICE: "cuda" # "cuda" or "cpu"